### ISSUE TITLE
镜像推送到 Harbor

### ISSUE THREAD

**Issue by navono** [docker-practice/drone-demo#1]
.drone.yml 里如何增加编译成镜像，然后推送至镜像托管服务，比如 Harbor？

**Comment by khs1994** [comment]
参考 http://plugins.drone.io/drone-plugins/drone-docker/

**Comment by navono** [comment]
我看过那文档。但是遇到了问题。我在 .drone.yml 是这么写的
```
- name: package
  image: plugins/docker
  settings:
    username: ping
    password: Ping12345
    registry: 10.30.26.86:8888
    repo:  10.30.26.86:8888/vxsip/golang-dem
    dockerfile: Dockerfile
    target: production
    tags: latest
```

`10.30.26.86:888` 是 Harbor 的地址。

在触发 Drone 后，出现：
```
1 | + /usr/local/bin/dockerd --data-root /var/lib/docker
-- | --
2 | time="2019-09-06T09:24:18Z" level=fatal msg="Error authenticating: exit status 1"

```

**Comment by khs1994** [comment]
非安全仓库登录肯定报错，设为非安全仓库

`settings:` 加上 `insecure:true`

**Comment by navono** [comment]
我是在 Docker for Win 上操作的。你指的是 `insecure-registries` 吗？

**Comment by khs1994** [comment]
`drone.yml` 文件。

```yaml
- name: package
  image: plugins/docker
  settings:
    username: ping
    password: Ping12345
    registry: 10.30.26.86:8888
    repo:  10.30.26.86:8888/vxsip/golang-dem
    dockerfile: Dockerfile
    target: production
    tags: latest
    insecure: true # 新增
```

**Comment by navono** [comment]
加上 `insercure` 还得加上 `volumes`。

```
- name: package
  image: plugins/docker:18.09.0
  settings:
    username: ping
    password: Ping12345
    registry: 10.30.26.86:8888
    repo:  10.30.26.86:8888/vxsip/golang-demo
    dockerfile: Dockerfile
    target: production
    tags: latest
    insecure: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
```

非常感谢。

想再问个问题，不知道你有没有用过这个插件 `appleboy/drone-ssh` 进行部署。
